tailwind.config.ts
#4
Tailwind Custom Theme 작성
purple의 경우 100~800까지 있고
lime, cherry는 light, main, dark 세가지 컬러셋 가지고 있습니다.
메인 컬러 외 모노톤은 neutral로 맞춰주세요.
=> Design: tailwind custom theme

src/components/common/Tag.tsx
#8
props (size, style, background) 에 따라 다양한 스타일을 지원하는 Tag 컴포넌트 구현 했습니다.
```
size?: 'small' | 'big';
style?: 'default' | 'retro' | 'time';
background?: 'dark' | 'medium' | 'light' | 'red';
```
(+ background 속성에 red 추가했습니다.)
>
=> feat: Tag 컴포넌트 구현

src/app/guild/page.tsx, src/components/guild/guild-fullimage.tsx, src/components/guild/guild-horizon.tsx, src/components/guild/guild-vertical.tsx, src/types/guild.ts
#1 
길드 타입 생성 -> 추후 필요한 데이터에 따라 변경 될 수 있음. 
수정시 types/guild.ts 파일을 수정하면 됨
길드 카드 horizon, vertical, fullImage 및 suspense용 스켈레톤 제작
>
레이아웃을 반응형으로 하고 컴포넌트는 고정된 크기로 하는 방법이 맞는 것인지
=> 1 feat guild card component

src/components/game/SelectedGameCard.tsx
#31 
SelectedGameCard 컴포넌트 작업했습니다.
- components > game  폴더 안에 있습니다.
- prop으로 game 데이터만 넘겨주면 됩니다.
- Game type을 컴포넌트 내부에 작성해두었는데, 태환님께서 이미 Game 타입을 정의해두신 것 같아서 태환님 코드 병합 이후에 수정하겠습니다.
- 컴포넌트에 `aspect-[410/180]` 이 클래스를 주어서 부모 컨텐츠의 사이즈 내에서 비율이 유지되게 구현했는데, 괜찮은지 질문드립니다.
=> feat: selected game card component

src/components/game/PickCard.tsx, src/components/game/PopularCard.tsx, src/components/game/SteamCard.tsx, src/types/game.ts
#3 
게임 카드 컴포넌트 작업했습니다.
PopularCard
PickCard
SteamCard
>
이미지의 경우 추후 변경 예정입니다.
=> #3 Feat/game card component

src/components/community/community-menu-bar.tsx, src/types/communityTags.ts
#39 
커뮤니티 상단 메뉴 바 구현
특정 태그 선택시 애니메이션 효과
>
=> feat : community menu bar

src/components/party/PartyCard.tsx, src/components/party/PartyLogCard.tsx
#54 
1. game 이름 하드코딩된 것 수정 
2. line-clamp-1 로 되어 있던 것 truncate로 수정했습니다. (PartyCard & PartyLogCard)
+ 추가로 hover 시에 보이는 오버레이 부분 css 수정했습니다. (absolute 부분 제거)
>
=> fix: fix party card component text ellipsis issue

src/components/common/SearchBar.tsx, src/components/common/category-menu.tsx, src/components/common/chip.tsx, src/components/guild/guild-search-component.tsx, src/components/party/party-search-component.tsx, src/components/ui/date-time-picker.tsx, src/types/Tags/partyTags.ts
#63 
길드 조회 필터 컴포넌트
파티 조회 필터 컴포넌트
>
url을 사용해서 상태를 저장합니다.
=> feat : filters

src/components/game/SelectedGameCard.tsx
#73 
SelectedGameCard 컴포넌트 타입 수정했습니다.
그리고 게임 이름 길어질 경우에 ellipsis 설정이 빠져 있어서 추가해두었습니다.
>
=> fix: fixed selected game card component type

src/app/game/page.tsx
=> feat: game main page

src/app/intro/GuildSection.tsx, src/app/intro/HeroSection.tsx, src/app/intro/PartySection.tsx
#102 
1. 카드 컴포넌트 사이즈 제한
2. GSAP 마커 노출 끄기
3. 게임 길드 컴포넌트 더미데이터 얹기 (기존 스켈레톤)
4. 픽셀 캐릭터 나오는 타이밍 조절
=> Fix: main 퍼블리싱 수정

src/app/game/page.tsx, src/app/guild/create/page.tsx, src/app/guild/list/page.tsx, src/app/guild/page.tsx, src/app/party/create/page.tsx, src/app/party/page.tsx
- #88 
- 파티/ 파티 생성 페이지
- 길드 / 길드 생성/리스트 페이지
- 게임 페이지
- padding 추가
>
=> Design: section top add padding

src/app/guild/[guildid]/admin/page.tsx, src/app/guild/[guildid]/page.tsx
#91 
길드 관리자 페이지 & 길드 상세 페이지 퍼블리싱
>
=> 91 feat 길드 관리자 페이지

src/app/community/create/page.tsx, src/components/community/TextEditor/index.tsx, src/components/community/TextEditor/style.css
#95 
커뮤니티 글 작성 페이지 ui 작업 했습니다.
- react-quill-new 사용해서 texteditor 추가해주었습니다.
- react-quill 이 무거워서 그런지 로딩이 좀 느린 것 같아서 skeleton 만들어서 적용해두었습니다.
- 상엽님 코드 참고해서 form 처리 해두었습니다.
- skeleton
>
=> feat: community create page publishing

package-lock.json, package.json
=> feat: axios install

.env.default, .gitignore, package-lock.json, package.json, src/utils/axiosInstance.ts
#122 
axios instance 생성 및 테스트
>
=> feat: axios instance 생성 및 테스트

src/app/party/components/UserInfoVertical.tsx
#118 
UserInfoVertical 컴포넌트 css를 수정하여 선택됐을 때 작아보이는 현상을 개선했습니다.
- 수정 전
- 수정 후
>
=> design: UserInfoVertical component css

src/constants/routes/index.ts, src/constants/routes/route.ts, src/constants/routes/user.ts
=> feat : 기본적인 파일

src/constants/routes/guild.ts, src/constants/routes/route.ts
#130 
길드 타입 수정 및 길드 관련 라우트 정의 했습니다.
>
=> feat: 길드 타입 수정 및 길드 라우트 정의

src/constants/routes/community.ts, src/constants/routes/guild.ts
#133 
- 길드 라우트 중에 동적 라우팅 경로 앞에 '/' 빠져있어서 추가했습니다.
- 커뮤니티 라우트 정의 했습니다.
>
=> feat: 커뮤니티 라우트 정의

src/app/game/list/page.tsx, src/components/game/PickCard.tsx, src/utils/dummyData.ts
=> feat : game list page

src/constants/routes/community.ts, src/constants/routes/game.ts, src/constants/routes/guild.ts, src/constants/routes/index.ts, src/constants/routes/party.ts, src/constants/routes/route.ts, src/constants/routes/user.ts
#141 
아래의 구조대로 라우트 수정하고, PATH에 각 라우트 추가해두었습니다.
>
=> feat: 전체 라우트 정리

src/api/members.ts, src/api/partyLog.ts, src/app/login/page.tsx, src/app/signup/page.tsx, src/app/signup/userSchema.ts, src/app/signup/userdata/page.tsx, src/components/ui/toast.tsx, src/hooks/useAxios.ts, src/stores/authStore.ts, src/types/Tags/userCategories.ts, src/types/user.ts
=> 152 feat members api

src/api/members.ts, src/api/partyLog.ts, src/app/login/page.tsx, src/app/login/steam/page.tsx, src/app/login/steam/style.css, src/app/signup/page.tsx, src/app/signup/steam/page.tsx, src/app/signup/steam/style.css, src/app/signup/userdata/component/cooler-category-menu.tsx, src/app/signup/userdata/page.tsx, src/constants/endpoints/member.ts, src/hooks/useAxios.ts, src/utils/typeConverter.ts, src/utils/uploadToS3.ts
=> 158 feat steam login

src/api/guild-member.ts, src/app/guild/[guildid]/admin/page.tsx, src/components/guildUser/GuildUser.tsx, src/constants/endpoints/guild-member.ts, src/types/user.ts
#154 
- 길드 멤버 리스트 나오고
- 권한 변경, 퇴출 버튼 기능 구현 중입니다.
>
=> Feat: 길드 멤버 api 기능 구현

src/api/guildBoard.ts, src/app/guild/[guildid]/community/[postid]/page.tsx, src/app/guild/[guildid]/community/page.tsx, src/components/common/capsule-category-menu.tsx, src/components/guild/guild-we-need-you.tsx, src/constants/endpoints/guild-board.ts, src/utils/typeConverter.ts
=> 162 feat guild board

src/api/members.ts, src/app/link/steam/page.tsx, src/app/link/steam/style.css, src/app/login/page.tsx, src/app/login/steam/page.tsx, src/stores/authStore.ts
=> 169 bug steam 로그인 리다이렉트 버그

src/api/guild-member.ts, src/app/guild/[guildid]/admin/page.tsx, src/components/guildUser/GuildUser.tsx
=> fix: guild member api 기능 구현 중간 commit

src/api/members.ts, src/components/common/Header/UserInfoLogin.tsx, src/components/common/Header/UserInfoLogout.tsx, src/components/common/Header/index.tsx, src/stores/authStore.ts
#175
쿠키값 남아있으면 자동 로그인까지 구현
로그인/로그아웃/마이페이지 이동까지는 구현해놨는데
마이페이지 로딩이 안되더라고요? 확인 필요할 것 같습니다.
>
=> Feat: header

.github/workflows/deploy.yml, Dockerfile
feat: dockerfile 및 CI/CD 구축
- 추가된 파일 목록
1. Dockerfile
2. .github/workflows/deploy.yml
=> feat: dockerfile 및 CI/CD 구축

src/api/game.ts, src/api/guildBoard.ts, src/app/guild/[guildid]/community/page.tsx, src/app/login/page.tsx, src/constants/endpoints/game.ts, src/constants/endpoints/guild-board.ts
=> 176 feat game api

.github/workflows/deploy.yml, Dockerfile, src/api/guild-member.ts, src/app/guild/[guildid]/admin/page.tsx, src/app/user/me/page.tsx, src/components/common/CustomPagination.tsx, src/components/ui/pagination.tsx
- #181 
- 길드 관리자 페이지에서 길드 멤버 API에 해당하는 부분 기능 구현 작업 했습니다.
- 추가로 길드 관리자 페이지는 길드 관리 - 길드 정보 변경, 길드 삭제 및 파티 생성 버튼과 승인 대기 중 섹션 남아있습니다.
>
=> Feat:  길드 멤버 aip / 길드 관리자 페이지 기능 구현

src/api/guildJoin.ts, src/app/guild/test/page.tsx, src/types/guildApi.ts
=> feat: guild join api

src/api/guild.ts, src/api/guildBoard.ts, src/api/guildJoin.ts, src/app/guild/test/page.tsx, src/constants/endpoints/guild-join.ts, src/constants/endpoints/guild.ts, src/types/guildApi.ts
#202 
- Guild Board API 검증 완료 했습니다.
- 길드 게시글 상세 정보에 **작성일자**와, **본인이 작성자인지 확인 할 수 있는 값**이 없는 것 같아서 확인 요청 드려놓은 상태입니다.
- Guild, GuildJoin, GuildBoard 통합 테스트 하면서 Guild, GuildJoin API에도 수정 사항 조금씩 있습니. (타입이나, 반환 값 관련)
>
=> 202 feat guild board api 검증

src/api/notification.ts, src/constants/endpoints/notification.ts
=> notification

src/api/party.ts
메인페이지에서 리스트 - 1개씩 불러와지던 버그 수정돼서
옵션값도 따라 수정했습니다.
=> Fix: 백엔드 수정에 따른 설정 변경

src/api/guild-member.ts, src/api/guild.ts, src/api/guildJoin.ts, src/app/guild/[guildid]/admin/page.tsx, src/app/guild/[guildid]/components/GuildBoardLatestSection.tsx, src/app/guild/[guildid]/components/GuildBoardLatestSectionSkeleton.tsx, src/app/guild/[guildid]/components/GuildBoardNoticeSection.tsx, src/app/guild/[guildid]/components/GuildBoardNoticeSectionSkeleton.tsx, src/app/guild/[guildid]/components/GuildInfoSection.tsx, src/app/guild/[guildid]/components/GuildInfoSectionSkeleton.tsx, src/app/guild/[guildid]/components/GuildMemberSection.tsx, src/app/guild/[guildid]/components/GuildMemberSectionSkeleton.tsx, src/app/guild/[guildid]/components/guildInfo.module.css, src/app/guild/[guildid]/page.tsx, src/app/guild/page.tsx, src/app/party/components/UserApprove.tsx, src/components/guildUser/GuildUser.tsx, src/types/guildApi.ts
#222 
- 길드 어드민 페이지 join 기능 연동
- 길드 상세 페이지 참여 버튼 조건부 렌더링 추가 (인원 마감, 승인 대기)
- 길드 상세 페이지 skeleton 적용
>
=> feat: 길드 어드민 페이지 join 기능 연동

src/api/members.ts, src/app/signup/userdata/page.tsx, src/constants/endpoints/member.ts
=> feat : s3 아바타

package-lock.json, package.json, src/app/party/create/page.tsx, src/components/common/GameSearch.tsx, src/components/ui/command.tsx
#233 
게임 검색 컴포넌트 제작했습니다
컴포넌트에 쿼리 입력시 해당 쿼리 기준으로 게임 정보 가져오고
appId(스팀)과 게임 이름 묶어서 객체로 return합니다.
=> Feat: 게임 서치 컴포넌트 제작

src/api/guild.ts, src/api/guildBoard.ts, src/app/guild/[guildid]/community/[postid]/guildCommunityDetail.module.css, src/app/guild/[guildid]/community/[postid]/page.tsx, src/app/guild/[guildid]/community/create/page.tsx, src/app/guild/[guildid]/community/page.tsx, src/app/guild/[guildid]/components/GuildBoardLatestSection.tsx, src/app/guild/[guildid]/components/GuildBoardNoticeSection.tsx, src/app/guild/page.tsx, src/components/community/TextEditor/index.tsx, src/components/community/common/avatar-name.tsx, src/components/community/input-image.tsx, src/components/community/post-image-long.tsx, src/components/community/post-image-short.tsx, src/components/community/post-long.tsx, src/components/community/post-short.tsx, src/components/guild/guild-we-need-you.tsx, src/types/community.ts, src/utils/removeHtmlTags.ts
#228
- 길드 커뮤니티 게시글 생성, 리스트, 상세 페이지 api 연동
- post card 컴포넌트 css 수정
>
=> feat: 길드 커뮤니티 게시글 생성, 리스트, 상세 페이지 연동

src/api/free-community.ts, src/components/community/post-image-long.tsx, src/constants/endpoints/free-community.ts
=> 230 feat 자유게시판 api

next.config.mjs, src/api/party.ts, src/api/partyLog.ts, src/app/party/components/UserInfoHorizontal.tsx, src/app/party/components/UserInfoVertical.tsx, src/app/party/log/[partyid]/components/PartyLogForm.tsx, src/app/party/log/[partyid]/components/PartyLogSkeleton.tsx, src/app/party/log/[partyid]/components/PostInfo.tsx, src/app/party/log/[partyid]/page.tsx, src/app/party/log/[partyid]/parsePartyLogData.ts, src/types/user.ts
- #191
- 파티 결과 페이지 기능 구현
- 파티 로그 api 기능 구현
>
=> Feat: #191 feat 파티 로그 api 기능구현

src/api/party.ts, src/app/party/create/page.tsx, src/app/party/page.tsx, src/components/game/SelectedGameCard.tsx, src/types/party.ts
#236 
1. 게임 선택 시 배너 바뀌는 기능 추가
2. 파티 생성시 태그 선택 추가
3. 백엔드 수정에 따른 gameId > appId 타입, 용어 변경
4. 파티 생성 페이지 input handling 에러 수정
5. 파티 index 페이지 이미지 로딩 에러 수정 및 인기 게임 리스트 수정
=> Feat: party create banner 및 오류 수정

src/app/party/list/page.tsx, src/components/party/party-search-component.tsx
=> feat : party time

src/api/guildBoard.ts, src/app/guild/[guildid]/community/[postid]/page.tsx, src/app/guild/[guildid]/community/create/page.tsx, src/app/guild/[guildid]/community/page.tsx, src/components/community/comment-card.tsx, src/types/community.ts
#237
- 길드 게시판 댓글 생성 및 삭제 기능 연동 (본인일 경우에만 삭제 버튼 보임)
- 좋아요 토글 css 수정
>
=> feat: 길드 게시판 댓글 기능 연동

src/app/guild/create/page.tsx, src/app/guild/list/page.tsx, src/components/common/SearchBar.tsx, src/components/guild/guild-search-component.tsx, src/types/guildApi.ts
#254 
- 길드 생성시 게임 추가 기능 연동
- 백엔드와 이야기해서 appId null 값 가능하도록 수정하긴 했는데, 이로 인해서 백엔드 검색로직에서 발생하는 에러가 수정되지 않았습니다.
- 그래서 일단 프론트에서는 필수 값으로 적용해두었고, 이후에 백엔드 로직 수정되면 반영하겠습니다.
- 길드 메인 게임 검색 기능 추가
>
=> feat: 길드 게임 검색 기능 연동

src/api/members.ts, src/app/guild/page.tsx, src/components/common/search-guild-with-game/index.tsx, src/components/game/SteamCard.tsx
=> 260 feat 보유게임으로 길드 탐색

src/app/game/page.tsx
=> fix button fix

src/components/common/Header/index.tsx
=> Fix: 헤더 라우팅 수정

next.config.mjs, src/app/intro/HeroSection.tsx, src/app/intro/ThreeController.tsx, src/app/page.tsx
#232 
모델렌더 버그 수정
섹션 안뜨는 문제 해결
use strict 껐습니다...!!
=> Fix: 메인페이지 로딩 에러 수정

src/app/game/list/page.tsx, src/app/guild/list/page.tsx, src/app/guild/page.tsx, src/app/party/list/page.tsx, src/components/common/search-guild-with-game/index.tsx, src/utils/dummyData.ts
=> 270 feat 메인페이지용 게임으로 길드 검새 기능 추가

src/api/game.ts, src/app/game/[gameid]/page.tsx, src/app/game/list/page.tsx, src/app/game/page.tsx, src/app/game/sections/hero-section.tsx, src/app/game/sections/steam-ranking-section.tsx, src/app/guild/list/page.tsx, src/app/guild/page.tsx, src/app/party/list/page.tsx, src/app/party/page.tsx
=> feat : 로띠 애니메이션 & 디자인

src/app/community/[postId]/page.tsx, src/app/community/create/page.tsx, src/app/community/page.tsx, src/app/guild/[guildid]/page.tsx, src/app/guild/create/page.tsx, src/components/community/community-menu-bar.tsx
#274 
- 길드 상세, 생성
- 자유게시판 생성, 댓글
(로그인 누르면 로그인 페이지 이동)
>
=> feat: 로그인 필요한 페이지들 예외처리

src/api/members.ts, src/api/notification.ts, src/app/game/sections/steam-ranking-section.tsx, src/app/layout.tsx, src/app/party/[partyid]/components/InfoAccordion.tsx, src/app/party/[partyid]/components/PartyContext.tsx, src/components/common/Header/UserInfoLogin.tsx, src/components/common/Header/notification-item.tsx, src/components/common/invite-modal.tsx, src/hooks/useAxios.ts, src/stores/inviteStore.ts
=> 277 feat 게임 메인 페이지 플레이타임 라우팅

src/api/members.ts, src/app/user/[userid]/page.tsx, src/app/user/me/modify/page.tsx, src/app/user/me/modify/style.css, src/app/user/me/page.tsx, src/components/game/PopularCard.tsx, src/components/party/PartyCard.tsx, src/components/party/PartyLogCard.tsx, src/constants/endpoints/member.ts, src/types/games.ts, src/utils/formatDate.ts
- #244 
- 마이페이지, 유저 정보 페이지 기능구현
>
=> Feat: 마이페이지, 유저 정보 페이지 api 기능 구현 #244

src/api/members.ts, src/app/party/[partyid]/components/InfoAccordion.tsx, src/components/common/Header/UserInfoLogin.tsx, src/components/common/Header/notification-item.tsx, src/components/ui/button.tsx
=> fix 모달창 열릴때 요청

src/app/community/[postId]/page.tsx, src/components/common/capsule-category-menu.tsx, src/components/guild/guild-we-need-you.tsx
#282 
길드 커뮤니티 메뉴바 수정 & postid 대소문자 수정
>
=> feat: 길드 커뮤니티 메뉴바 수정 & postid 대소문자 수정

src/app/guild/components/PopularGuildList.tsx, src/app/guild/page.tsx, src/components/community/comment-card.tsx
댓글 컴포넌트의 유저 이미지에 dummy_profile 적용했습니다.
>
=> Fix: 커뮤니티 댓글 유저 이미지 fallback

src/app/party/components/UserInfoHorizontal.tsx, src/app/party/components/UserInfoVertical.tsx, src/app/party/log/[partyid]/components/DefaultInfo.tsx, src/app/party/log/[partyid]/components/PostInfo.tsx, src/app/party/log/[partyid]/page.tsx, src/app/party/log/[partyid]/parsePartyLogData.ts, src/app/user/[userid]/page.tsx, src/components/guildUser/GuildUser.tsx, src/types/party.ts
- #285 
- 아바타 라우팅 설정
- 파티 결과 페이지 백그라운드
>
=> Fix: 기타 수정 #285

src/api/game.ts, src/api/notification.ts, src/app/game/[gameid]/page.tsx, src/app/game/page.tsx, src/components/common/Header/UserInfoLogin.tsx
=> fix : 빌드 오류 수정

src/api/party.ts, src/app/party/[partyid]/components/InfoAccordion.tsx, src/app/party/[partyid]/components/PartyContext.tsx, src/app/party/[partyid]/page.tsx, src/app/party/components/UserApprove.tsx, src/app/party/page.tsx, src/components/party/PartyCard.tsx, src/constants/endpoints/member.ts, src/types/party.ts
#297 
파티 API 수정에 따른 파티 페이지 수정 들어갔습니다
연관된 페이지 및 파티 로그 기능 검증 필요
=> Fix: 파티 페이지 API 수정에 따른 구조 변경

src/app/guild/components/PopularGameCard.tsx, src/app/guild/page.tsx, src/app/intro/TotalSection.tsx, src/components/common/search-guild-with-game/index.tsx, src/components/community/post-image-short.tsx, src/components/community/post-short.tsx, src/utils/dummyData.ts
- 메인 페이지용 더미 데이터
- 길드 페이지용 게임 더미데이터 
>
=> Feat: main dummy data

src/api/party.ts, src/app/game/page.tsx, src/app/party/[partyid]/components/InfoChatting.tsx, src/app/party/[partyid]/components/PartyContext.tsx, src/app/party/create/page.tsx, src/types/party.ts
=> feat date time and chat

src/api/members.ts, src/app/game/page.tsx, src/app/guild/page.tsx, src/app/layout.tsx, src/app/link/steam/innerPage.tsx, src/app/login/page.tsx, src/app/login/steam/innerPage.tsx, src/app/signup/steam/innerPage.tsx
=> 로그인 회원가입 토스트 메세지 & 라우팅 게임 페이지 더미데이터 

src/components/common/Header/index.tsx
=> fix : me 에러 수정

src/api/steamImg.ts, src/app/community/[postId]/page.tsx, src/app/guild/[guildid]/community/[postid]/page.tsx, src/app/guild/list/innerPage.tsx, src/app/intro/TotalSection.tsx, src/app/login/page.tsx, src/app/party/[partyid]/components/InfoAccordion.tsx, src/app/party/[partyid]/page.tsx, src/app/party/[partyid]/partyDetail.module.css, src/app/party/list/innerPage.tsx, src/app/signup/page.tsx, src/components/common/Header/UserInfoLogin.tsx, src/components/party/PartyCard.tsx
=> design: 전체 CSS 수정

src/app/intro/PartySection.tsx
#323 
좀 더 자연스럽게 움직일 수 있도록 타이밍 조절했습니다.
=> Fix: GSAP 타이밍 조절

src/app/guild/page.tsx, src/components/common/search-guild-with-game/index.tsx
=> fix: 게임으로 길드 검색

src/app/intro/HeroSection.tsx
=> fix: add main button routing

src/app/game/[gameid]/page.tsx, src/app/guild/[guildid]/admin/page.tsx, src/app/guild/page.tsx, src/components/common/Header/UserInfoLogin.tsx, src/components/common/Header/notification-item.tsx
=> 331 feat 길드 초대 기능 게임 상세 버그 픽스

src/hooks/useAxios.ts
=> 333 feat 액시오스

src/hooks/useAxios.ts
=> 333 feat 액시오스 (#336)

next.config.mjs, src/hooks/useAxios.ts
=> MIXED CONTENT ERROR NEXT.JS 프록시 설정 

next.config.mjs, package-lock.json, package.json, src/api/steam-video-proxy.ts, src/app/game/[gameid]/page.tsx
=> Feat: video proxy

src/api/game.ts, src/api/party.ts, src/app/game/[gameid]/page.tsx, src/app/game/list/innerPage.tsx, src/app/login/page.tsx, src/app/party/list/innerPage.tsx, src/components/common/Header/UserInfoLogin.tsx, src/components/common/Header/index.tsx, src/hooks/useStomp.ts
=> 배포 전 버그 픽스

src/app/party/[partyid]/components/InfoAccordion.tsx, src/app/party/[partyid]/components/PartyContext.tsx, src/types/party.ts
=> fix : ownerId

src/app/login/page.tsx, src/app/login/steam/innerPage.tsx, src/app/signup/page.tsx, src/app/signup/steam/innerPage.tsx
=> fix : 로그인 페이지 하단 버튼 안보이는 오류

src/app/game/[gameid]/page.tsx, src/components/game/PickCard.tsx
=> 352 feat party 카드 텍스트 너무 길게 출력되면 자르는 기능

src/app/community/create/page.tsx, src/app/game/[gameid]/page.tsx, src/app/game/list/innerPage.tsx, src/app/game/page.tsx, src/app/guild/create/page.tsx, src/app/guild/page.tsx, src/app/party/[partyid]/components/PartyContext.tsx, src/app/party/create/page.tsx, src/components/common/GameSearch.tsx, src/components/common/search-guild-with-game/index.tsx, src/components/guild/guild-search-component.tsx, src/components/party/party-search-component.tsx, src/components/svg/rotate_fill.tsx, src/stores/authStore.ts, src/types/games.ts, src/utils/dummyData.ts
=> 358 feat 더미 데이터 db에 없는 게임인 문제 수정 + hydration 에러 수정

src/app/guild/page.tsx, src/components/common/search-guild-with-game/index.tsx, src/utils/dummyData.ts
=> 364 feat 게임으로 길드 검색 수정

.github/workflows/deploy.yml, src/app/community/[postId]/page.tsx, src/app/guild/[guildid]/admin/page.tsx, src/app/guild/[guildid]/community/[postid]/page.tsx, src/app/guild/[guildid]/page.tsx, src/app/party/[partyid]/components/InfoAccordion.tsx, src/app/user/[userid]/page.tsx, src/app/user/me/innerPage.tsx, src/app/user/me/myPage.module.css, src/components/common/Header/UserInfoLogin.tsx
#360 
- 미 로그인 시 좋아요, 댓글 누르면 toast 띄우기
- 조회수 제거
- 유저 페이지 스와이퍼 적용
- 마이페이지 로그아웃 시 예외처리
- 길드 어드민 페이지 수정 버튼 제거
- 파티 상세 유저 이미지 잘림 수정
- 수락 또는 거절한 알림 보이지 않게 처리
>
=> fix: 자잘한 버그 수정

.github/workflows/deploy.yml, src/app/community/[postId]/page.tsx, src/app/community/create/page.tsx, src/app/game/[gameid]/page.tsx, src/app/game/list/innerPage.tsx, src/app/game/page.tsx, src/app/guild/[guildid]/admin/page.tsx, src/app/guild/[guildid]/community/[postid]/page.tsx, src/app/guild/[guildid]/page.tsx, src/app/guild/create/page.tsx, src/app/guild/page.tsx, src/app/party/[partyid]/components/InfoAccordion.tsx, src/app/party/[partyid]/components/PartyContext.tsx, src/app/party/create/page.tsx, src/app/user/[userid]/page.tsx, src/app/user/me/innerPage.tsx, src/app/user/me/myPage.module.css, src/components/common/GameSearch.tsx, src/components/common/Header/UserInfoLogin.tsx, src/components/common/search-guild-with-game/index.tsx, src/components/guild/guild-search-component.tsx, src/components/party/party-search-component.tsx, src/components/svg/rotate_fill.tsx, src/stores/authStore.ts, src/types/games.ts, src/utils/dummyData.ts
=> 배포 0417 10:45

src/app/game/list/components/CustomDateTimePicker.tsx, src/app/game/list/components/CustomGameSearch.tsx, src/app/game/list/components/CustomGenres.tsx, src/app/game/list/components/CustomMacSwitch.tsx, src/app/game/list/components/CustomPlayerType.tsx, src/app/game/list/components/CustomReleaseStatus.tsx, src/app/game/list/components/CustomResetComponent.tsx, src/app/game/list/components/ImFeelingLuckyBtn.tsx, src/app/game/list/page.tsx, src/app/game/list/stores/gameSearchStore.ts, src/components/common/CustomPagination.tsx, src/components/common/EmptyLottie.tsx, src/components/common/HeroSwiperBanner.tsx
=> 367 feat 목록페이지 리팩토링

src/app/game/list/components/CustomDateTimePicker.tsx, src/app/game/list/components/SuspendedGameDisplay.tsx, src/app/game/list/getGames.ts, src/app/game/list/page.tsx, src/hooks/getQueryClient.ts, src/hooks/useReactQuery.tsx
=> feat : Tanstack with ServerComponent
